package net.capozi.unilib.datagen;

import net.capozi.unilib.CoreTags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.item.Items;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class CoreItemTagProvider extends FabricTagProvider.ItemTagProvider {
    protected void configure(RegistryWrapper.WrapperLookup arg) {
        getOrCreateTagBuilder(CoreTags.Craftable.CRAFTABLE_ITEMS)
                .add(Items.ACACIA_BOAT)
                .add(Items.ARROW)
                .add(Items.ARMOR_STAND)
                .add(Items.BLACK_DYE)
                .add(Items.BLUE_DYE)
                .add(Items.BONE_MEAL)
                .add(Items.BOOK)
                .add(Items.BEETROOT_SOUP)
                .add(Items.BIRCH_BOAT)
                .add(Items.BIRCH_CHEST_BOAT)
                .add(Items.BLAZE_POWDER)
                .add(Items.BOW)
                .add(Items.BOWL)
                .add(Items.BREAD)
                .add(Items.BRICK)
                .add(Items.BROWN_DYE)
                .add(Items.BUCKET)
                .add(Items.BUNDLE)
                .add(Items.CHAINMAIL_BOOTS)
                .add(Items.CHAINMAIL_HELMET)
                .add(Items.CHAINMAIL_CHESTPLATE)
                .add(Items.CHAINMAIL_LEGGINGS)
                .add(Items.CHARCOAL)
                .add(Items.CARROT_ON_A_STICK)
                .add(Items.CLOCK)
                .add(Items.COD_BUCKET)
                .add(Items.COMPASS)
                .add(Items.COOKED_BEEF)
                .add(Items.COOKED_CHICKEN)
                .add(Items.COOKED_COD)
                .add(Items.COOKED_MUTTON)
                .add(Items.COOKIE)
                .add(Items.COOKED_PORKCHOP)
                .add(Items.COOKED_RABBIT)
                .add(Items.COOKED_SALMON)
                .add(Items.COPPER_INGOT)
                .add(Items.CROSSBOW)
                .add(Items.CYAN_DYE)
                .add(Items.DARK_OAK_BOAT)
                .add(Items.DARK_OAK_CHEST_BOAT)
                .add(Items.DIAMOND_AXE)
                .add(Items.DIAMOND_BOOTS)
                .add(Items.DIAMOND_HELMET)
                .add(Items.DIAMOND_HOE)
                .add(Items.DIAMOND_CHESTPLATE)
                .add(Items.DIAMOND_LEGGINGS)
                .add(Items.DIAMOND_PICKAXE)
                .add(Items.DIAMOND_SHOVEL)
                .add(Items.DIAMOND_SWORD)
                .add(Items.DRAGON_BREATH)
                .add(Items.MUSIC_DISC_5)
                .add(Items.ELYTRA)
                .add(Items.ENCHANTED_BOOK)
                .add(Items.ENDER_EYE)
                .add(Items.FERMENTED_SPIDER_EYE)
                .add(Items.FILLED_MAP)
                .add(Items.FIREWORK_ROCKET)
                .add(Items.FIREWORK_STAR)
                .add(Items.FLOWER_BANNER_PATTERN)
                .add(Items.FLINT_AND_STEEL)
                .add(Items.FISHING_ROD)
                .add(Items.FURNACE_MINECART)
                .add(Items.GLASS_BOTTLE)
                .add(Items.GOLD_INGOT)
                .add(Items.GOLDEN_APPLE)
                .add(Items.GLISTERING_MELON_SLICE)
                .add(Items.GLOBE_BANNER_PATTERN)
                .add(Items.GOLDEN_AXE)
                .add(Items.GOLDEN_BOOTS)
                .add(Items.GOLDEN_CARROT)
                .add(Items.GOLDEN_CHESTPLATE)
                .add(Items.GOLDEN_HELMET)
                .add(Items.GOLDEN_HOE)
                .add(Items.GOLDEN_LEGGINGS)
                .add(Items.GOLDEN_PICKAXE)
                .add(Items.GOLDEN_SHOVEL)
                .add(Items.GOLDEN_SWORD);
    }
    public CoreItemTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }
}
